"""add Name to Author table

Revision ID: 9ca006aa0338
Revises: 4fab784f33c8
Create Date: 2021-05-29 11:19:26.044237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca006aa0338'
down_revision = '4fab784f33c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_column('author', 'name')
    # ### end Alembic commands ###
